# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-27 14:34
from __future__ import unicode_literals

from django.db import migrations
from datetime import datetime

def load_persons(apps, schema_editor):
    Person = apps.get_model("test_filter", "Person")

    for i in range(3):
        person = Person(id=i, first_name='person', last_name=str(i))
        person.save()

def delete_persons(apps, schema_editor):
    Person = apps.get_model('test_filter', "Person")

    Person.objects.all().delete()

def load_sessions(apps, schema_editor):
    Person = apps.get_model("test_filter", "Person")
    PersonSession = apps.get_model("test_filter", "PersonSession")

    for i in range(3):
        for j in range(3):
            person_session = PersonSession(id=i*3 + j,
                                           person=Person.objects.get(id=i),
                                           start_time=datetime(year=2000, month=j + 1, day=1, hour=13, minute=2),
                                           end_time=datetime(year=2000, month=j + 1, day=1, hour=14, minute=2))
            person_session.save()
def delete_sessions(apps, schema_editor):
    PersonSession = apps.get_model('test_filter', 'PersonSession')

    PersonSession.objects.all().delete()

def load_billings(apps, schema_editor):
    PersonSession = apps.get_model('test_filter', 'PersonSession')
    Billing = apps.get_model('test_filter', "Billing")

    for i in range(3):
        for j in range(3):
            billing = Billing(id=i*3 + j,
                              session=PersonSession.objects.get(id=i*3 + j),
                              status='DE' if (i + j + 1) % 3 <= 1 else 'BA')
            billing.save()

def delete_billings(apps, schema_editor):
    Billing = apps.get_model('test_filter', "Billing")

    Billing.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('test_filter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_persons, delete_persons),
        migrations.RunPython(load_sessions, delete_sessions),
        migrations.RunPython(load_billings, delete_billings)
    ]
